[theme]
font = "sans serif"

[theme.light]
primaryColor = "#FF4B4B"
backgroundColor = "#FEFAF4"
secondaryBackgroundColor = "#EFE5DA"
textColor = "#262730"

[theme.dark]
primaryColor = "#FF7979"
backgroundColor = "#111820"
secondaryBackgroundColor = "#1D2733"
textColor = "#E7EDF5"
